#
# YAML Config file for evmcmd
#

# Application config items
application:
   prompt: "evmcmd>"
   instpath: "./"

# Connection config items
connection:
   host: "10.16.132.167"
   port: "443" # Use this in case the CFME engine is listening on another port
   user: "admin"
   pass: "smartvm"

aws:
   default_region: 'us-west-1'
   access_key_id: AKIAJ6HD47S3QCEPXREQ
   secret_access_key: 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

   # My Root AWS ID
